require './unit/syntax-tree-builder.coffee'
require './unit/check-factory.coffee'
require './unit/type.coffee'
require './unit/boolean.coffee'
require './unit/number.coffee'
require './unit/property.coffee'
require './unit/either.coffee'
require './unit/array.coffee'
require './unit/equal.coffee'

