language: node_js
matrix:
  include:
    - node_js: '10'
    - node_js: '8'
    - node_js: '6'
    - node_js: '4'
install:
  - 'npm i -g npm@latest'
  - 'npm install'
script:
  - 'npm run clean-build'
  - 'npm run all-tests'

