language: node_ js
node_js:
  - '6'
  - '4'
  - '0.12'
  - '0.10'
env:
  - 'LINT=yes'
  - 'LINT=""'
#matrix:
#  include:
#    - node_js: '6'
#      env: LINT=yes
#    - node_js: '4'
#    - node_js: '0.12'
#    - node_js: '0.10'
install:
  - 'npm install'
script:
  - 'node -v'
  - 'npm -v'
  - 'if [ -n "$LINT" ]; then npm run lint; else true; fi'
  - 'npm test'

